module.exports = {
    env: {
        es6: true,
        node: true,
        mocha: true,
    },
    parserOptions: {
        ecmaVersion: 2021,
        sourceType: 'module',
        ecmaFeatures: {
            legacyDecorators: true,
            experimentalDecorators: true,
        },
    },
    parser: '@babel/eslint-parser',
    extends: [
        'eslint:recommended',
        'plugin:promise/recommended',
        'plugin:unicorn/recommended',
    ],
    rules: {
        'array-bracket-newline': ['error', 'consistent'],
        'array-bracket-spacing': 'error',
        'array-callback-return': ['error', {
            allowImplicit: true,
        }],
        'array-element-newline': ['error', 'consistent'],
        'arrow-spacing': ['error', {
            before: true,
            after: true,
        }],
        'brace-style': ['error', '1tbs'],
        'camelcase': ['error', {
            ignoreDestructuring: true,
            ignoreImports: true,
            allow: ['/A-Z/', '^vehicle_lpn$'],
        }],
        'comma-dangle': ['error', 'only-multiline'],
        'comma-spacing': ['error', {
            before: false,
            after: true,
        }],
        'comma-style': ['error', 'last'],
        'curly': ['error', 'multi-line'],
        'default-case': ['error', {
            commentPattern: '^no default$',
        }],
        'dot-notation': 'error',
        'eol-last': ['error', 'always'],
        'eqeqeq': ['error', 'always', {
            null: 'ignore',
        }],
        'func-call-spacing': ['error', 'never'],
        'function-paren-newline': ['error', 'consistent'],
        'indent': ['error', 4, {
            MemberExpression: 'off',
            SwitchCase: 1,
        }],
        'jsx-quotes': ['error', 'prefer-double'],
        'key-spacing': ['error', {
            beforeColon: false,
            afterColon: true,
            mode: 'strict',
        }],
        'keyword-spacing': ['error', {
            before: true,
            after: true,
        }],
        'linebreak-style': ['error', 'unix'],
        'lines-between-class-members': ['error', 'always', {
            exceptAfterSingleLine: true,
        }],
        'max-len': ['error', {
            code: 140,
            ignoreStrings: true,
            ignoreRegExpLiterals: true,
            ignoreUrls: true,
            ignoreTemplateLiterals: true,
            ignoreComments: true,
        }],
        'newline-per-chained-call': ['error', {
            ignoreChainWithDepth: 3,
        }],
        'no-console': 'error',
        'no-else-return': 'error',
        'no-implicit-coercion': 'error',
        'no-multiple-empty-lines': ['error', {
            max: 1,
        }],
        'no-multi-spaces': ['error', {
            ignoreEOLComments: false,
            exceptions: {
                Property: false,
                VariableDeclarator: false,
                ImportDeclaration: false,
            },
        }],
        'no-throw-literal': 'error',
        'no-trailing-spaces': 'error',
        'no-unneeded-ternary': 'error',
        'no-unused-vars': 'off',
        'no-useless-concat': 'error',
        'no-useless-escape': 'error',
        'no-useless-return': 'error',
        'no-var': 'error',
        'object-curly-newline': ['error', {
            consistent: true,
        }],
        'object-curly-spacing': ['error', 'always'],
        'object-property-newline': ['error', {
            allowAllPropertiesOnSameLine: true,
        }],
        'object-shorthand': 'error',
        'one-var': ['error', 'never'],
        'padded-blocks': ['error', 'never'],
        'prefer-const': 'error',
        'prefer-promise-reject-errors': 'error',
        'prefer-spread': 'error',
        'quote-props': ['error', 'consistent-as-needed', {
            numbers: true,
        }],
        'quotes': ['error', 'single', {
            allowTemplateLiterals: true,
            avoidEscape: false,
        }],
        'require-await': 'error',
        'semi': ['error', 'never'],
        'sort-imports': ['error', {
            ignoreCase: false,
            ignoreDeclarationSort: true,
            ignoreMemberSort: false,
            memberSyntaxSortOrder: ['none', 'all', 'multiple', 'single'],
        }],
        'space-before-blocks': ['error', 'always'],
        'space-before-function-paren': ['error', {
            anonymous: 'never',
            named: 'never',
            asyncArrow: 'always',
        }],
        'space-infix-ops': 'error',
        'spaced-comment': ['error', 'always'],
        'switch-colon-spacing': 'error',
        'yoda': 'error',
        'unicorn/catch-error-name': ['error', {
            name: 'err',
        }],
        'unicorn/consistent-function-scoping': 'off',
        'unicorn/filename-case': 'off',
        'unicorn/new-for-builtins': 'off',
        'unicorn/no-array-callback-reference': 'off',
        'unicorn/no-array-for-each': 'off',
        'unicorn/no-array-reduce': 'off',
        'unicorn/no-lonely-if': 'off',
        'unicorn/no-null': 'off',
        'unicorn/no-object-as-default-parameter': 'off',
        'unicorn/no-this-assignment': 'off',
        'unicorn/numeric-separators-style': 'off',
        'unicorn/prefer-number-properties': 'off',
        'unicorn/prefer-spread': 'off',
        'unicorn/prefer-switch': 'off',
        'unicorn/prefer-ternary': 'off',
        'unicorn/throw-new-error': 'off',
        'unicorn/prevent-abbreviations': 'off',
    }
}